added whoami command
drogue-iot/drg pull request #40
Opened 2021-04-08 23:12 UTC by rishabh-vasudevan

I have made another function in utils because the last function that printed the version took &Result<config> as its argument, so I made another function that does the same thing but with config:&Config as argument.

If there is anything that I should have done differently or something you would like me to add please let me know.

2021-04-09 14:41 UTC, jbtrystram requested changes

2021-04-09 14:41 UTC, jbtrystram commented on src/arguments.rs
> +            SubCommand::with_name(Other_commands::whoami.as_ref())
who ami needs a `--token` argument that do the same as the `token` subcommand

2021-04-09 14:41 UTC, jbtrystram commented on src/main.rs
> +        util::print_version_config(&config);
```suggestion
        util::print_version(Ok(config));
```

2021-04-09 14:44 UTC, jbtrystram commented
Also make sure to run `cargo fmt` on your code before submitting a PR. Don't pay attention to the "packit" failing tests

2021-04-23 08:03 UTC, jbtrystram commented
@rishabh-vasudevan  are you planning to update this PR ?

2021-04-23 08:09 UTC, rishabh-vasudevan commented
> @rishabh-vasudevan are you planning to update this PR ?

Yeah I am planning to work on this. I have my college exams till sunday, will work on it after they get over.

2021-04-23 08:12 UTC, jbtrystram commented
Sure ! I don't want to pressure you in anyway, I just wanted to check in :) Good luck on your exams

2021-05-01 19:55 UTC, closed without merging