adding whoam i command
drogue-iot/drg pull request #58
Opened 2021-05-01 20:00 UTC by rishabh-vasudevan

i have been able to print cluster adress, version and default app(if any). I have also added the --token argument but I am not able check whether the argument --token was there or not in the command. Could you please help me with the syntax of adding a check of whether the argument --token was present or not.

2021-05-03 08:07 UTC, jbtrystram requested changes

2021-05-03 08:07 UTC, jbtrystram commented on src/main.rs
> +            util::print_version(&Ok(config));
Please move this logic to the `util` module. main is already quite long and messy so it's better if we keep only the arg-related suff here IMO.

2021-05-03 08:07 UTC, jbtrystram commented on src/main.rs
> +            openid::print_token(&context);
I think what you look for is : 
```suggestion
        if matches.is_present("token") {
            openid::print_token(&context);
```

2021-05-03 21:02 UTC, rishabh-vasudevan commented
I have made the changes. Please let me know if I should have done something differently.

2021-05-05 08:24 UTC, jbtrystram requested changes

2021-05-05 11:13 UTC, rishabh-vasudevan commented on src/arguments.rs
> +    let _token_arg = Arg::with_name(Other_commands::token.as_ref())
I did that by mistake. I was trying to remove the warning that was coming and added the _ absentmindedly.

2021-05-06 20:28 UTC, jbtrystram approved these changes

2021-05-06 20:28 UTC, jbtrystram commented on src/arguments.rs
>      token,
Can you also update the `token` command and mark is at deprecated ? Pointing to the new command would also be helpful for users :)

2021-05-06 20:28 UTC, jbtrystram commented on src/arguments.rs
> +                        .help("print a valid bearer toke for the drogue cloud instance."),
token

2021-05-09 17:21 UTC, merged